name: Test Suite

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: windows-latest
            python-version: 3.9

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v2
    - name: Fetch private vc2_data_tables repo
      uses: actions/checkout@v2
      with:
        repository: bbc/vc2_data_tables
        path: vc2_data_tables
        token: ${{ secrets.PAT }}
    - name: Install with test dependencies
      shell: bash
      run: |
        (cd vc2_data_tables/ && python setup.py develop)
        python setup.py develop
        python -m pip install -r requirements-test.txt
    - name: Run test suite
      run: |
        py.test tests/
