name: Test Suite

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v2
    - name: Fetch private vc2_data_tables repo
      uses: actions/checkout@v2
      with:
        repository: bbc/vc2_data_tables
        path: vc2_data_tables
        token: ${{ secrets.PAT }}
    - name: Install with test dependencies
      shell: bash
      run: |
        (cd vc2_data_tables/ && python setup.py develop)
        python setup.py develop
        python -m pip install -r requirements-test.txt
    - name: Run test suite
      run: |
        py.test tests/
